# Site settings
title: "Aarya Gupta"
description: "Portfolio of Aarya Gupta"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Aarya Gupta"
resume_title: |
  Placement Cell IIITD • Reliance Foundation Scholar  <br>
  • UG Researcher @ {MIDAS, NETSEC, NAS} Labs IIITD <br>• Junior @ IIITD
  
# used for the contact button in _layouts/resume.html
resume_contact_email:           "aarya22006@iiitd.ac.in"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "Phone No."
# resume_contact_address:         "Address"

resume_header_contact_info:     "header_contact_info"
display_header_contact_info:    "false"

resume_header_intro: "<p>
As a tech enthusiast with a solid foundation in algorithms, logic, and critical thinking, I explore AI, cybersecurity, and circuit design. I enjoy using Figma and Miro for creative projects, have a keen interest in psychology, and value fitness. I aim to articulate ideas effectively and contribute to technology.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Aarya-Gupta"
  resume_twitter_url:           "https://twitter.com/aaryathisside"
  # resume_dribbble_url:          "insert Dribble URL here"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/aarya-gupta-professional/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://aarya-gupta.github.io/web/"
  resume_medium_url:            "https://medium.com/@aarya22006"
  resume_discord_url:           "https://discord.com/invite/8jhC4pFa"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
